<p></p>
<hr>
<div class="box box-success filter-box">
	<div class="box-header with-border bg-gray">
		<div class="box-title text-muted" data-toggle="collapse" data-target="#filterForm">
		    <a href="javascript:void(0)" class="btn btn-default btn-flat">
				<i class="fa fa-lg fa-fw fa-bars"></i> Filtracja
		    </a>
		</div>
		<div class="box-tools pull-right" style="max-width: 50%;width: 30%;float: right;top:10px;position: static">
			<div class="input-group" >
				<input type="text" name="table_search" ng-model="query.search" class="form-control pull-right" placeholder="<?= $table->getSearchLabel(); ?>">

				<div class="input-group-btn">
					<button type="submit" class="btn btn-default btn-flat"><i class="fa fa-search"></i></button>
				</div>
			</div>
	</div>
</div>
<div class="box-body no-padding collapse bg-gray" id="filterForm" style="border-radius: 0">
	<div style="padding:15px 10px;">
<?= $table->hasFilterForm() ?  $this->myForm()->nosubmit()->vertical($table->getFilterForm()->prepare(),(int)$table->getFilterForm()->getOption('columns')) : null; ?>
	</div>
</div>
<div class="box-footer never-hide bg-gray" style="">            
	<!-- <div class="btn btn-flat btn-danger btn-labeled btn-sm" ng-class="{disabled: !hasFilter()}" ng-click="ClearFilter()">
	<span class="btn-label"><i class="fa fa-times"></i></span>
	Wyczyść filtry
	</div> -->
<!-- <div class="btn btn-flat btn-default btn-labeled btn-sm" ng-click="setInitialState()">
<span class="btn-label"><i class="fa fa-history"></i></span>
Ustawienia Domyślne
</div> -->
<span class="label" ng-repeat="label in query.filter">
	<!-- <pre>{{label|json}}</pre> -->

</span>


<div class="btn btn-flat btn-danger btn-labeled btn-sm pull-right" ng-click="setInitialState()">
	<span class="btn-label"><i class="fa fa-times"></i></span>
	Wyczyść filtry
</div>


<div class="alert alert-info" role="alert" ng-if="totalUnfilter > 0">
	Znaleziono 
	<strong>{{total}}</strong>
	<ng-pluralize count="total" offset=2
              when="{'0': 'elementów',
              		 'one': 'element',
                     'few': 'elementy',
                     'many': 'elementów',                     
                     'other': 'elementów'}">
	</ng-pluralize>
	spełniających podane kryteria z
	<strong>{{totalUnfilter}} </strong>
	znajdujących się w bazie
</div>
<!-- <span class='label label-info label-btn-align'>
&nbsp;Znaleziono elementów: <strong>{{total}}</strong> z <strong>{{totalUnfilter}}</strong>
</span> -->
</div>
</div>

<p></p>

<style>
.filter-box .bg-gray.box-header.with-border,
.filter-box .bg-gray {
    border-color: #bbb;
    background-color: #f6f6f6 !important;
}
.filter-box .alert-info {
    color: #31708f !important;
    background-color: #d9edf7 !important;
    border-color: #bce8f1;
    float: left;
    /*width: 100%;*/
    padding: 5px 15px;
    /*margin: 10px 0;*/
    margin:0;
}

</style>