<? $this->inlineScript()->appendScript("angular.module( 'myApp').requires.push('doctrine-table');");?>
<? if($table->hasCookieKey())echo '<script>var coookiekey=\''.$table->getCookieKey().'\'</script>';?>
<? if($table->hasInitalState()): echo '<script>var InitalState='.json_encode($table->getInitalState()).';</script>';?>
<? else: ?><script>var InitalState=null;</script><? endif; ?>





<div class="box box-success" dt-wrapper ng-init="init('<?= $table->getQuerySuffix();?>')">
<div class="box-header with-border">
    <div class="row">
        <div class="col-md-6">
            <h3 class="box-title"><?= $table->getLabel(); ?></h3>
        </div>
        <div class="col-md-6 text-right">
        <? if($table->getFootButtons()):?>
            <div class="box-tools">
                <? $footBtns = $table->getFootButtons();if($footBtns)foreach($footBtns as $btn)echo $this->footButton($btn) .'&nbsp;&nbsp;';?>        
            </div>
        <? endif; ?>
        </div>
    </div>
    <? if($table->hasFilterForm() || $table->hasSearch())echo  $this->partial('partial/filter'); ?>

</div>


<div class='box-body no-padding' style="position: relative;" id="no-more-tables">

<div class="overlay ng-hide-animate" ng-hide="!loading" >
    <div class="overlay-spinner">
        <p><i class="fa fa-5x fa-spinner fa-spin"></i></p>
        <p>trwa ładowanie</p>
    </div>
</div>

<table class='table table-striped table-hover table-bordered'  >
    <thead>
        <tr>
            <th style="width:25px">#</th>
            <? 
            $columns = null;
            foreach($table->getColumns() as $column)$columns .= $this->HeaderColumn()->angular($column); 
            echo $columns;
            ?>
            <th colspan="<?//= count($table->getAclButtons()) ?>" class='text-right'>Opcje</th>
        </tr>
    </thead>
    <tbody>
        <tr ng-hide="items.length > 0">
            <td colspan="<?= count($table->getButtons()) + count($table->getColumns()) +1 ?>" class="text-center">
            <p>- brak wyników -</p>
            </td>
        </tr>
        <tr ng-repeat="(key,item) in items" dt-repeat ng-class="item.row_class">
            <!-- <td class="hidden-mobile">{{(key*1+(query.page-1)*query.itemCount+1)|number}}</td> -->
            <td class="hidden-mobile">
                <span class="badge">{{(key*1+(query.page-1)*query.itemCount+1)|number}}</span>
            </td>
            <? foreach($table->getColumns() as $column): ?>
            <?= $this->BodyColumn()->angular($column); ?>
            <? endforeach; ?>
            <td class="buttons text-right" >
                <span ng-repeat="btn in item.buttons">
                <a href="{{btn.url}}" class="{{btn.class}}" ng-if="btn.allowed" uib-tooltip="{{btn.title}}" tooltip-append-to-body="true" tooltip-placement="left">
                    <i class="{{btn.icon}}"></i>
                </a>

                <a href="{{btn.url}}" class="btn disabled btn-default btn-circle" ng-if="!btn.allowed" 
                    uib-tooltip="{{'Nie masz uprawnien do : ' + btn.title}}" tooltip-append-to-body="true" tooltip-placement="left"
                >
                    <i class="fa fa-times"></i>
                </a>
                </span>
            <? 
                // if($table->getButtons())foreach($table->getButtons() as $btn)echo $this->BodyButton()->angular($btn);
            ?>
            </td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th>#</th>
            <? echo $columns; ?>
            <th colspan="<?= count($table->getButtons()) ?>" class='text-right'>Opcje</th>
        </tr>
    </tfoot>
</table>
</div>
<div class="box-footer clearfix">
<span class="" style="font-weight: 500;font-size: 1em">
            Znaleziono 
            <strong>{{total}}</strong>
            <ng-pluralize count="total" offset=2
                      when="{'0': 'elementów',
                             'one': 'element',
                             'few': 'elementy',
                             'many': 'elementów',                     
                             'other': 'elementów'}">
            </ng-pluralize>
            spełniających podane kryteria z
            <strong>{{totalUnfilter}} </strong>
            znajdujących się w bazie
        </span>
    <ul class="pagination pagination-sm no-margin pull-right">
        <li><a href="javascript:void(0)" ng-click="paginator.first()"><i class="fa fa-angle-double-left"></i></a></li>
        <li><a href="javascript:void(0)" ng-click="paginator.prev()"><i class="fa fa-angle-left"></i></a></li>
        <li ng-if="paginator.hasMoreBefore()"><a>...</a></li>

        <li ng-repeat="p in paginator.range()" ng-class='{active: p == query.page}'><a href="javascript:void(0)" ng-click="paginator.setPage(p)">{{p}}</a></li>

        <li ng-if="paginator.hasMoreAfter()"><a>...</a></li>
        <li><a href="javascript:void(0)" ng-click="paginator.next()"><i class="fa fa-angle-right"></i></a></li>
        <li><a href="javascript:void(0)" ng-click="paginator.last()"><i class="fa fa-angle-double-right"></i></a></li>
    </ul>
      <?//= $this->paginationControl($table->getPaginator(),'Sliding','partial/table_paginator'); ?>
</div>
</div>

<script type="text/javascript">
<? $this->inlineScript()->captureStart();?>
 $(function () {
    $('.collapsed-box .box-body').hide();
    $('table .icheck').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });

    $('body').on('click','.confirm',function(e){
        e.preventDefault();
        var self = $(this);
        $('#modal-delete').modal('show');
        var url = $(this).attr('href');
        $('#modal-delete').find('.btn-danger').on('click',function(){
            $(this).unbind('click');
            $.ajax({
                type : 'DELETE',
                url : url,
                datatype : 'json',
                complete : function(response){
                    $('#modal-delete').modal('hide');
                    self.parentsUntil('tr').parent().remove();
                }
            })
        });
    })
  });   
<? $this->inlineScript()->captureEnd();?>
</script>

<style>
td > div{
    font-size: 90%;
}
#filterForm.collapse{
    display: block;
    height: 0;
    overflow: hidden;
    visibility: hidden;
}
#filterForm.collapse.in{
    height: auto;
    visibility: visible;
        overflow: visible;
}
.order-th{
    padding-right: 20px !important;
}
.overlay{
    position: absolute;
    width: 100%;
    height: 100%;
    opacity: 1; 
    
}
.overlay .overlay-spinner{
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%,-50%);
    text-align: center;
    transition: opacity 1s ease-out,height 1s ease-out;
    
}
/*@-webkit-keyframes fadeOut {
    0% { opacity: 1;height: 100%; }
    99% { opacity: 0;height: 100%; }
    100% { opacity: 0;height: 0%;  }
}*/
@keyframes fadeIn {
    from { opacity: 0;height: 100%; }
    to { opacity: 1;height: 100%; }
}
@keyframes fadeOut {
    from { opacity: 1;height: 100%; }
    to { opacity: 0;height: 100%; }
}
.overlay.ng-hide{
    /*-webkit-animation: fadeOut 0.4s;*/
    animation: fadeOut 0.4s;
    height:0;
    overflow: hidden;
}
.overlay:not(.ng-hide){
    /*animation: fadeIn 0.2s;*/
}

.angular-table-select option {
    display: none;
}
.angular-table-select option[ng-value] {
    display: block;
}
</style>


<div class="modal modal-danger fade" id="modal-delete" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span></button>
        <h4 class="modal-title">Ostrzerzenie przed usunięciem!</h4>
      </div>
      <div class="modal-body">
        <p>Czy na pewno chcsesz usunąć element?</p>
      </div>
      <div class="modal-footer">
        <!-- <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button> -->
        <button type="button" class="btn btn-flat btn-danger btn-labeled">
            <span class="btn-label"><i class="fa fa-trash fa-lg fa-fw"></i></span>
            Tak usuń
        </button>
        <button type="button" class="btn btn-flat btn-default btn-labeled"  data-dismiss="modal">
            <span class="btn-label"><i class="fa fa-times fa-lg fa-fw"></i></span>
            Anuluj
        </button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>